name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: devsecops-454508

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDS }}'

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker
        working-directory: ./spring-petclinic

      - name: (Optional) Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./spring-petclinic

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./spring-petclinic
          push: true
          tags: |
            gcr.io/${{ env.GCP_PROJECT_ID }}/spring-petclinic:latest
            gcr.io/${{ env.GCP_PROJECT_ID }}/spring-petclinic:${{ github.sha }}
