name: Build, Scan and Push Docker Image to GCR

on:
  workflow_run:
    workflows: ["Terraform CI"]  # 👈 This is the name of the workflow it depends on
    types:
      - completed

env:
  GCP_PROJECT_ID: devsecops-454508
  REGION: us-central1

jobs:
  build-scan-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if Terraform workflow succeeded
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDS }}'

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev
        working-directory: ./spring-petclinic

      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/docker-repo/spring-petclinic:latest ./spring-petclinic

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/docker-repo/spring-petclinic:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Push Docker image to GCR
        run: |
          docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/docker-repo/spring-petclinic:latest
